### ISSUE TITLE
3.4 - Etsy - Corbin Otwell

### ISSUE THREAD

**Issue by cbotwell** [TIY-LR-FEE-2015-June/assignments#103]
## Deliverables
- [x] A publicly visible website (gh-pages, divshot, heroku, etc...)
## Requirements
- [x] Normal Mode
  - [x] Utilize the data for whatever search term you use - [DATA
    HERE](https://api.etsy.com/v2/listings/active.js?api_key=cdwxq4soa7q4zuavbtynj8wx&keywords=whiskey&includes=Images,Shop&sort_on=score)
  - [x] Use Bourbon / Neat to help you out (optional, but suggested)
  - [x] You are free to change the search term to whatever you'd like.
  - [x] We haven't covered how to fetch data using JavaScript, so follow the instructions to use `loadEtsy`
  - [x] Everything should be styled as closely as possible, including the Header/Footer
  - [x] You should implement hover events and link the items to their proper Etsy product pages
  - [x] Unless you do the bonus question #2, you can just put random links in your sidebar.
  - [x] Do not use jQuery - we haven't covered it so this SHOULDN'T be a problem
  - [x] Also, no need to make any of the form elements work.
- [ ] Hard Mode
  - [x] Create your own API token by signing up as an [Etsy developer](https://www.etsy.com/developers/)
  - [x] Replace the API token in `load-etsy.js`
  - [ ] Pull the categories from the data to create the sidebar, with links that filter the listings.
  - [ ] Use `onsubmit` on form elements so that the main area is switched out when a user submits the search form but it doesn't reload the entire page.
  - [x] Implement loading spinners while data is loading (you can use the `immediate` argument of `loadEtsy` to do this)
  - [ ] Implement the sorting dropdown.

**Comment by cbotwell** [comment]
:link: [Corbin's 3.4 Pull Request](https://github.com/cbotwell/3.4-etsy/pull/1)

**Comment by cbotwell** [comment]
:link: [Corbin's 3.4 GH Page](http://cbotwell.github.io/3.4-etsy/)

**Comment by rtablada** [comment]
@cbotwell it looks pretty good so far.

# Todos
- [ ] The header bar and content of the listings should be line up on the right side
- [ ] Try to make your images cropped and stick to an aspect ratio for the top section of listings so that the grid stays lined up

**Comment by cbotwell** [comment]
Got both of those todos implemented! :smile:

**Comment by rtablada** [comment]
(yಠ,ಠ)y update todo checkboxes!

@cbotwell other than not updating the checkboxes... :star:
