### ISSUE TITLE
3.4-Etsy-ColemanCox

### ISSUE THREAD

**Issue by ColemanCox** [TIY-LR-FEE-2015-June/assignments#106]
## Deliverables
- [ ] A publicly visible website (gh-pages, divshot, heroku, etc...)
## Requirements
- [ ] Normal Mode
  - [ ] Utilize the data for whatever search term you use - [DATA
    HERE](https://api.etsy.com/v2/listings/active.js?api_key=cdwxq4soa7q4zuavbtynj8wx&keywords=whiskey&includes=Images,Shop&sort_on=score)
  - [ ] Use Bourbon / Neat to help you out (optional, but suggested)
  - [ ] You are free to change the search term to whatever you'd like.
  - [ ]  We haven't covered how to fetch data using JavaScript, so follow the instructions to use `loadEtsy`
  - [ ] Everything should be styled as closely as possible, including the Header/Footer
  - [ ] You should implement hover events and link the items to their proper Etsy product pages
  - [ ] Unless you do the bonus question #2, you can just put random links in your sidebar.
  - [x] Do not use jQuery - we haven't covered it so this SHOULDN'T be a problem
  - [ ] Also, no need to make any of the form elements work.
- [ ] Hard Mode
  - [ ] Create your own API token by signing up as an [Etsy developer](https://www.etsy.com/developers/)
  - [ ] Replace the API token in `load-etsy.js`
  - [ ] Pull the categories from the data to create the sidebar, with links that filter the listings.
  - [ ] Use `onsubmit` on form elements so that the main area is switched out when a user submits the search form but it doesn't reload the entire page.
  - [ ] Implement loading spinners while data is loading (you can use the `immediate` argument of `loadEtsy` to do this)
  - [ ] Implement the sorting dropdown.

**Comment by ColemanCox** [comment]
https://github.com/ColemanCox/3.4-Etsy/pull/1

**Comment by rtablada** [comment]
@ColemanCox 

# Todo
- [ ] Upload latest build to GH Pages for comments and notes
- [ ] Add link in this issue to your GH Pages url

**Comment by rtablada** [comment]
@ColemanCox still missing latest code and GH Pages & GH page link here in your issue.

**Comment by rtablada** [comment]
@ColemanCox still no GH Page link
