### ISSUE TITLE
3.4-Etsy-Brent-Thomas

### ISSUE THREAD

**Issue by Brent-M-Thomas** [TIY-LR-FEE-2015-June/assignments#107]
Deliverables
- [x] A publicly visible website (gh-pages, divshot, heroku, etc...)

Normal Mode
- [x] Utilize the data for whatever search term you use - DATA HERE
- [x] Use Bourbon / Neat to help you out (optional, but suggested)
- [x] You are free to change the search term to whatever you'd like.
- [x] We haven't covered how to fetch data using JavaScript, so follow the instructions to use loadEtsy
- [x] Everything should be styled as closely as possible, including the Header/Footer
- [x] You should implement hover events and link the items to their proper Etsy product pages
- [x] Unless you do the bonus question #2, you can just put random links in your sidebar.
- [x] Do not use jQuery - we haven't covered it so this SHOULDN'T be a problem
- [x] Also, no need to make any of the form elements work.

Hard Mode
- [ ] Create your own API token by signing up as an Etsy developer
- [ ] Replace the API token in load-etsy.js
- [ ] Pull the categories from the data to create the sidebar, with links that filter the listings.
- [ ] Use onsubmit on form elements so that the main area is switched out when a user submits the search form but it  doesn't reload the entire page.
- [ ] Implement loading spinners while data is loading (you can use the immediate argument of loadEtsy to do this)
- [ ] Implement the sorting dropdown.

**Comment by rtablada** [comment]
@Brent-M-Thomas 

# Todos
- [ ] Deliverables should be in your issue's todo list (even if it is one item that can be assumed from now on)
- [ ] Commit and push latest code to github (you should be doing this at every stopping point)
- [ ] Create pull request (this should be the first thing you do once an assignment is handed out)
- [ ] Link to Pull Request in this issue
- [ ] Commit and send build of latest attempt to GH Pages so that I can give you feedback
- [ ] Link to GH Pages url in this issue

**Comment by Brent-M-Thomas** [comment]
https://github.com/Brent-M-Thomas/3.4-etsy/pull/1

**Comment by rtablada** [comment]
@Brent-M-Thomas missing GH Page link.

**Comment by rtablada** [comment]
@Brent-M-Thomas still no GH Page link

**Comment by Brent-M-Thomas** [comment]
<a href="http://brent-m-thomas.github.io/3.4-etsy"> GH page link</a>

**Comment by Brent-M-Thomas** [comment]
@rtablada 
 added gh page link

**Comment by rtablada** [comment]
@Brent-M-Thomas remember to update your GH pages and push your latest code!

**Comment by Brent-M-Thomas** [comment]
@rtablada Latest code pushed and deployed to gh pages.  Does that look alright?

**Comment by rtablada** [comment]
@Brent-M-Thomas looking a lot better.
