### ISSUE TITLE
3.4-Alia Borroho

### ISSUE THREAD

**Issue by aliaborroho** [TIY-LR-FEE-2015-June/assignments#108]
Deliverables
- [x] A publicly visible website (gh-pages, divshot, heroku, etc...)
## Requirements
- [x]  Normal Mode
  - [x] Utilize the data for whatever search term you use - [DATA
    HERE](https://api.etsy.com/v2/listings/active.js?api_key=cdwxq4soa7q4zuavbtynj8wx&keywords=whiskey&includes=Images,Shop&sort_on=score)
  - [x] Use Bourbon / Neat to help you out (optional, but suggested)
  - [x] You are free to change the search term to whatever you'd like.
  - [x] We haven't covered how to fetch data using JavaScript, so follow the instructions to use `loadEtsy`
  - [x] Everything should be styled as closely as possible, including the Header/Footer
  - [x] You should implement hover events and link the items to their proper Etsy product pages
  - [x] Unless you do the bonus question #2, you can just put random links in your sidebar.
  - [x] Do not use jQuery - we haven't covered it so this SHOULDN'T be a problem
  - [x] Also, no need to make any of the form elements work.
- Hard Mode
  - [x] Create your own API token by signing up as an [Etsy developer](https://www.etsy.com/developers/)
  - [x] Replace the API token in `load-etsy.js`
  - [x] Pull the categories from the data to create the sidebar, with links that filter the listings.
  - [ ] Use `onsubmit` on form elements so that the main area is switched out when a user submits the search form but it doesn't reload the entire page.
  - [x] Implement loading spinners while data is loading (you can use the `immediate` argument of `loadEtsy` to do this)
  - [ ] Implement the sorting dropdown.

**Comment by aliaborroho** [comment]
https://github.com/aliaborroho/3.4-etsy/pull/1

**Comment by rtablada** [comment]
@aliaborroho 

# Todo
- [ ] Fix the missing font-awesome.css link [look at the "Relative Font Paths" Section of the SASS notes](http://rtablada.gitbooks.io/front-end-engineering-june-2015/content/week-2/day-3/sass.html)
- [ ] Upload latest build to GH Pages for comments and notes
- [ ] Add link in this issue to your GH Pages url

**Comment by rtablada** [comment]
@aliaborroho missing gh page link

**Comment by aliaborroho** [comment]
http://aliaborroho.github.io/3.4-etsy/

@rtablada I cant get the thing to load in the center info, is it the spinner

**Comment by rtablada** [comment]
@aliaborroho let's review the JS from this assignment
