### ISSUE TITLE
3.4-etsy-Daniel Condit

### ISSUE THREAD

**Issue by DanielCondit** [TIY-LR-FEE-2015-June/assignments#111]
Deliverables
- [x] A publicly visible website (gh-pages, divshot, heroku, etc...)

Requirements
- [ ] Normal Mode
  - [x] Utilize the data for whatever search term you use - [DATA HERE](https://api.etsy.com/v2/listings/active.js?api_key=cdwxq4soa7q4zuavbtynj8wx&keywords=whiskey&includes=Images,Shop&sort_on=score)
  - [x] Use Bourbon / Neat to help you out (optional, but suggested)
  - [x] You are free to change the search term to whatever you'd like.
  - [x] We haven't covered how to fetch data using JavaScript, so follow the instructions to use `loadEtsy`
  - [ ] Everything should be styled as closely as possible, including the Header/Footer
  - [ ] You should implement hover events and link the items to their proper Etsy product pages
  - [ ] Unless you do the bonus question #2, you can just put random links in your sidebar.
  - [x] Do not use jQuery - we haven't covered it so this SHOULDN'T be a problem
  - [ ] Also, no need to make any of the form elements work.
- [ ] Hard Mode
  - [ ] Create your own API token by signing up as an [Etsy developer](https://www.etsy.com/developers/)
  - [ ] Replace the API token in `load-etsy.js`
  - [ ] Pull the categories from the data to create the sidebar, with links that filter the listings.
  - [ ] Use `onsubmit` on form elements so that the main area is switched out when a user submits the search form but it doesn't reload the entire page.
  - [ ] Implement loading spinners while data is loading (you can use the `immediate` argument of `loadEtsy` to do this)
  - [ ] Implement the sorting dropdown.

**Comment by DanielCondit** [comment]
https://github.com/DanielCondit/3.4-etsy/pull/1

**Comment by rtablada** [comment]
@DanielCondit 

# Todos
- [x] Line up your todo list better, right now you have extra `+` before the nested items that is making things all appear on one level
- [x] Push to github pages and post link to gh-pages in this issue

I will be able to give further notes when I am able to see what you have on GH Pages

**Comment by DanielCondit** [comment]
http://danielcondit.github.io/3.4-etsy/

**Comment by rtablada** [comment]
@DanielCondit Looking good so far!

# Updated Todos
- [ ] Continue work on header to include links and search bar (don't worry about the drop down [yet])
- [ ] Listings have rounded borders on the bottom, but the top is still showing up as square - check your overflows
- [ ] Test different search terms to see if pictures and rows stay in line (Images should crop) http://www.mademyday.de/css-height-equals-width-with-pure-css.html
- [ ] Continue work on bottom navigation and footer
