### ISSUE TITLE
4.1 - Beer - Corbin Otwell

### ISSUE THREAD

**Issue by cbotwell** [TIY-LR-FEE-2015-June/assignments#113]
## Deliverables
- [x] A publicly visible website (gh-pages) and link to this in your issue
## Requirements
- [x] Recreate the beer layout using SCSS, Bourbon, and Neat
- [x] Use handlebars with a template to add beer items from the provided data to the DOM
- [x] Use `array.forEach` to iterate over the array of beer items rather than Handlebars `{{#each}}{{/each}}` loops
- [x] Clicking on a button on the page uses `classList` to switch between list mode and grid mode
- [x] Variables in `app.js` should not pollute the global scope (think self invoking anonymous functions)
- [x] Do not use jQuery - we haven't covered it so this SHOULDN'T be a problem

**Comment by cbotwell** [comment]
:link: [Corbin's 4.1 Pull Request](https://github.com/cbotwell/4.1-beer/pull/1)

**Comment by cbotwell** [comment]
:link: [Corbin's 4.1 GH Page](http://cbotwell.github.io/4.1-beer/)

**Comment by rtablada** [comment]
@cbotwell 

# TODOS
- [ ] `text-overflow: ellipsis;` on the beer description.
- [ ] Vertically center things in list view (after using span-columns for width percentages, try overriding the `display` of things to `inline-block` and then `float: none`. From there `vertical-align` should work.)
