### ISSUE TITLE
4.4-jquery-events-marvin-santiago

### ISSUE THREAD

**Issue by marvinsantiago** [TIY-LR-FEE-2015-June/assignments#135]
### ToDos / Plan of Attack
- [x] New folder / git/bower/npm init
- [x] Boilerplates files
- [x] Build tools
- [x] Bower install - jquery, neat, reset-css, fontawesome
- [x] git commit, hub create, & push master
- [x] Create and move over to develop branch
- [x] Add HTML to represent accordion
- [x] Commit, push develop
- [x] Create PR & link in issue
- [x] Style header button
- [x] Style 'open' header (hulk mode) & hover
- [x] Style sublist (the stuff that shows up when its open)
- [x] Create a variable with jQuery to get our accordion buttons
  - [x] Test that a click even works (test when onclick alert 'hey')
- [x] Make button change to hulk mode on click
- [x] Make sub menu open on click
- [x] Make other sub menus close on click

**Comment by marvinsantiago** [comment]
https://github.com/santiagomarvin/4.4-jquery-events/pull/1

**Comment by marvinsantiago** [comment]
http://santiagomarvin.github.io/4.4-jquery-events/accordion.html

**Comment by marvinsantiago** [comment]
ToDo - Keyboard
- [x] Create HTML, CSS, JS files
- [x] Boilerplate
- [x] Add HTML for keyboard
- [x] Style keyboard
- [x] Add function for keys when clicked
- [x] Test the functionality of keys

**Comment by rtablada** [comment]
@santiagomarvin do you have a link for the Normal mode on the keyboard? The accordian looks pretty good, I would just clean up some separating borders between elements in your sub menus.

**Comment by rtablada** [comment]
@santiagomarvin any link for your keyboard progress?

**Comment by marvinsantiago** [comment]
@rtablada - http://santiagomarvin.github.io/4.4-jquery-events/keyboard.html
