### ISSUE TITLE
5.1-github-profile - marvin santiago

### ISSUE THREAD

**Issue by marvinsantiago** [TIY-LR-FEE-2015-June/assignments#146]
### Deliverables
- [x] A publicly visible website on `gh-pages`
### Requirements
- [x] No JSHint warnings or errors
- [x] No JS errors in the browser
- [x] All functions and code should work according to the following description.
- [x] Personalized plan of attack
## Normal Mode
- [x] Write `$.ajax()` requests to:
  - [ ] `https://api.github.com/users/<username>`
  - [ ] `https://api.github.com/users/<username>/repos`
- [x] After loading data from the Github API, write at least the following information to the DOM:
  - [x] name
  - [x] blog
  - [x] location
  - [x] email
  - [x] avatar_url
  - [x] html_url
  - [x] and list all of your repositories
### Tasks
- [x] Read and interact with the examples in [jQuery Fundamentals: AJAX &
  Deferreds](http://jqfundamentals.com/chapter/ajax-deferreds)
- [x] Watch the video [What the heck is the event loop
  anyway?](https://www.youtube.com/watch?v=8aGhZQkoFbQ)

**Comment by marvinsantiago** [comment]
https://github.com/santiagomarvin/5.1-github-profile/pull/1

**Comment by marvinsantiago** [comment]
http://santiagomarvin.github.io/5.1-github-profile/

**Comment by rtablada** [comment]
@santiagomarvin the profile side of things looks really good, the repos section is a bit rough in terms of styles.

**Comment by rtablada** [comment]
@santiagomarvin also, do you have a plan of attack/todo list?

**Comment by marvinsantiago** [comment]
###ToDos / Plan of Attack
- [x] New folder / git/bower/npm init
- [x] Boilerplates files
- [x] Build tools
- [x] Bower install - jquery, neat, reset-css, fontawesome
- [x] git commit, hub create, & push master
- [x] Create and move over to develop branch
- [x] Add HTML to represent github page
- [x] Commit, push develop
- [x] Create PR & link in issue
- [x] Create template for profile and repo section
- [x] Setup ajax in js file to pull data into HTML
- [x] Style page

**Comment by marvinsantiago** [comment]
@rtablada updated repo section

**Comment by rtablada** [comment]
@santiagomarvin Looks good for the requirements, after the weekend you may want to tweak some things if you listed this in your portfolio. But :+1:
