### ISSUE TITLE
5.1-GitHub Profile-ColemanCox

### ISSUE THREAD

**Issue by ColemanCox** [TIY-LR-FEE-2015-June/assignments#149]
### Deliverables
- [ ] A publicly visible website on `gh-pages`
### Requirements
- [ ] No JSHint warnings or errors
- [ ] No JS errors in the browser
- [ ] All functions and code should work according to the following description.
- [ ] Personalized plan of attack
## Normal Mode
- [ ] Build a github profile app that prints out some info from the Github API and your repos. **For the design, you should recreate the Github Repos Tab to the best of your ability**.
- [ ] Write `$.ajax()` requests to:
  - [ ]  `https://api.github.com/users/<username>`
  - [ ]  `https://api.github.com/users/<username>/repos`
- [ ] After loading data from the Github API, write at least the following information to the DOM:
  - [ ] name
  - [ ] blog
  - [ ] location
  - [ ] email
  - [ ] avatar_url
  - [ ] html_url
  - [ ] and list all of your repositories
### Tasks
- [ ] Read and interact with the examples in [jQuery Fundamentals: AJAX &
  Deferreds](http://jqfundamentals.com/chapter/ajax-deferreds)
- [ ] Watch the video [What the heck is the event loop
  anyway?](https://www.youtube.com/watch?v=8aGhZQkoFbQ)
## Nightmare Mode
- [ ] Implement the Contributions tab of your profile page.
  This can be implemented as a separate set of `html` and `js` (you'll probably want to share your `css` to a good point).

**Comment by rtablada** [comment]
@ColemanCox missing a plan of attack and links to your Pull Request and Github Pages build.

**Comment by rtablada** [comment]
@ColemanCox see above
