### ISSUE TITLE
5.1-github-profile-Daniel Condit

### ISSUE THREAD

**Issue by DanielCondit** [TIY-LR-FEE-2015-June/assignments#158]
### Deliverables
- A publicly visible website on `gh-pages`
### Requirements
- No JSHint warnings or errors
- No JS errors in the browser
- All functions and code should work according to the following description.
- Personalized plan of attack
## Normal Mode

Build a github profile app that prints out some info from the Github API and your repos. **For the design, you should recreate the Github Repos Tab to the best of your ability**.

> Github tab page: https://github.com/rtablada?tab=repositories

The information from the Github API that you will display includes information from your github user account and repositories.
- [x] Write `$.ajax()` requests to:
  - [x] `https://api.github.com/users/<username>`
  - [x] `https://api.github.com/users/<username>/repos`
- [x] After loading data from the Github API, write at least the following information to the DOM:
  - [x] name
  - [x] blog
  - [x] location
  - [x] email
  - [x] avatar_url
  - [x] html_url
  - [x] and list all of your repositories
### Tasks
- [x] Read and interact with the examples in [jQuery Fundamentals: AJAX &
  Deferreds](http://jqfundamentals.com/chapter/ajax-deferreds)
- [x] Watch the video [What the heck is the event loop
  anyway?](https://www.youtube.com/watch?v=8aGhZQkoFbQ)

**Comment by DanielCondit** [comment]
Pull request:

https://github.com/DanielCondit/5.1-github-profile/pull/1

GH page:

http://danielcondit.github.io/5.1-github-profile/

**Comment by rtablada** [comment]
@DanielCondit any updated TODOs and a link to your build on Github Pages?

**Comment by rtablada** [comment]
@DanielCondit ![Buler](https://media1.giphy.com/media/sW6P26sp3HFvy/200_s.gif)

**Comment by rtablada** [comment]
@DanielCondit still missing a GH Page link

**Comment by rtablada** [comment]
@DanielCondit GH Pages?

**Comment by rtablada** [comment]
@DanielCondit ![Hello](http://i450.photobucket.com/albums/qq229/murderofcrows_2008/Hello.gif)
