### ISSUE TITLE
1.3-iron-news-marvin-santiago

### ISSUE THREAD

**Issue by marvinsantiago** [TIY-LR-FEE-2015-June/assignments#23]
- [x] A Pull request including
  - [x] `index.html`
  - [x] A linked CSS file in the location of your choice
##### Requirements
- [x] Valid, semantic, accessable HTML
- [x] Valid CSS
- [x] At least one git commit (with a message) every hour that you're working on this project
- [x] No table layouts (you won't be able to just copy paste the HTML from hacker news)
- [x] Hard Requirements
  - [x] Improve the user prompts with
    - Hover states for links
  - [x] Make the different articles "zebra striped"
- [ ] Extra Hard Requirements
  - [ ] Replace the "Login" link in the nav bar with a "Account" drop down menu that has links to "Login" and "Signup"

**Comment by marvinsantiago** [comment]
https://github.com/santiagomarvin/1.3-iron-news/pull/1

**Comment by rtablada** [comment]
# Todo
- [ ] Fix Navbar

**Comment by rtablada** [comment]
Looks like you were about half done with the drop down. Don't worry about coming back to it though
