### ISSUE TITLE
1.1-Personal Website-Alia Borroho

### ISSUE THREAD

**Issue by aliaborroho** [TIY-LR-FEE-2015-June/assignments#24]
To do list for day 1: 
- [x] An issue in the class repo titled 1.1 - Personal Website -- {{YOUR_NAME}} with:
  checkboxes as below under Requirements
- [x] A repository named 1.1-Personal-Website containing at least:
- [x] index.html
- [x] A Pull Request (PR) in your 1.1-Personal-Website repo:
- [x] from branch develop
- [x] into branch master
- [x] A comment on your Issue with a link to your PR

**Comment by aliaborroho** [comment]
https://github.com/aliaborroho/1.1-Basic-git/pull/1

**Comment by rtablada** [comment]
@aliaborroho please update the todos for this issue to show as checkboxes: https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments

From now on, we will not be using inline styles on our HTML elements, instead we will use CSS files for reuse.

I have also updated and made comments on the file changes as to some things to look out for: https://github.com/aliaborroho/1.1-Basic-git/pull/1/files

**Comment by rtablada** [comment]
@aliaborroho 

# Todo
- [ ] Your picture is wrapped in a link that goes to an invalid page. Just include an image
- [ ] the links at the bottom of the page should be `a` tags with a set `href`
- [ ] Clean up the indenting of your HTML
