### ISSUE TITLE
1.3 - Iron News - Jacklyn Carroll

### ISSUE THREAD

**Issue by jacklynlee31** [TIY-LR-FEE-2015-June/assignments#25]
Requirements
- [x] Valid, semantic, accessable HTML
- [x] Valid CSS
- [x] At least one git commit (with a message) every hour that you're working on this project
- [x] No table layouts (you won't be able to just copy paste the HTML from hacker news)

Hard Requirements
Improve the user prompts with
- [x] Hover states for links
- [x] Make the different articles "zebra striped"

Extra Hard Requirements
- [x] Replace the "Login" link in the nav bar with a "Account" drop down menu that has links to "Login" and "Signup"

**Comment by jacklynlee31** [comment]
https://github.com/jacklynlee31/1.3-iron-news/pull/1

**Comment by rtablada** [comment]
# Todos
- [ ] Make articles 2 lines instead of one (this will be a bit more tricky)
- [ ] Fix nav bar jumping to two different lines
- [x] Fix css path
