### ISSUE TITLE
1.3-iron-news-daniel-condit

### ISSUE THREAD

**Issue by DanielCondit** [TIY-LR-FEE-2015-June/assignments#27]
Deliverables
- [x] A Pull request including
  - [x] `index.html`
  - [x] A linked CSS file in the location of your choice
  
  Requirements
- [x] Valid, semantic, accessable HTML
- [x] Valid CSS
- [x] At least one git commit (with a message) every hour that you're working on this project
- [x] No table layouts (you won't be able to just copy paste the HTML from hacker news)
- [ ] Hard Requirements
  - [ ] Improve the user prompts with
    - [ ] Hover states for links
  - [x] Make the different articles "zebra striped"
- [ ] Extra Hard Requirements
  - [ ] Replace the "Login" link in the nav bar with a "Account" drop down menu that has links to "Login" and "Signup"

**Comment by DanielCondit** [comment]
I have completed my page but missed some of the hard and extra hard requirements when I have time in the course I will go back and update the page.

The mane issues I had with this page was organizing my list items but thanks to the help of a class member I got it fixed.

Assignment is ready to be graded.

**Comment by rtablada** [comment]
# Todo
- [ ] Link to PR
- [ ] No Margin around the list items in the main list

**Comment by rtablada** [comment]
@DanielCondit marking as incomplete since this has not been turned in to spec.

And some new notes:
- The footer is not centered on larger screens...

![screen shot 2015-07-14 at 10 24 25 pm](https://cloud.githubusercontent.com/assets/2532004/8690216/1c8592e8-2a77-11e5-9456-f44da8fc3cc2.png)

**Comment by DanielCondit** [comment]
Pull request:

https://github.com/DanielCondit/1.3-iron-news/pull/1

**Comment by rtablada** [comment]
@DanielCondit footer is still off center on large screens.

**Comment by DanielCondit** [comment]
Fixed centering issue with footer, should be ready for turn in.
