### ISSUE TITLE
1.4-tshirts-marvin-santiago

### ISSUE THREAD

**Issue by marvinsantiago** [TIY-LR-FEE-2015-June/assignments#30]
- [x] A pull request with code to recreate the layout and transitions below
- [x] 3 wide grid with max-width so that images do not stretch
- [x] Hover state for all of the buttons on the bottom
- [x] Pop up menus above the bottom menu
- [ ] Hard Mode
  - When a user clicks on the store item show the back side using a 3d card

**Comment by marvinsantiago** [comment]
Working on layout

**Comment by marvinsantiago** [comment]
https://github.com/santiagomarvin/1.4-tshirts/pull/1

**Comment by rtablada** [comment]
# Todo
- [ ] Fix broken grid
- [ ] Try hard mode

**Comment by rtablada** [comment]
@santiagomarvin the grid is still broken at mid to small screen sizes, you should be able to fix this with some adjustments to width on `img` and a few small tweaks to make the grid drop down to different rows on smaller screens
