### ISSUE TITLE
1.4-tshirts-Brent-Thomas

### ISSUE THREAD

**Issue by Brent-M-Thomas** [TIY-LR-FEE-2015-June/assignments#36]
a git repo containing:
- [x] index.html
- [x] stylesheets (in a css/ directory)
- [x] images folder
  with any images you used with your design
  Requirements
- [x] A pull request with code to recreate the layout and transitions below
- [x] 3 wide grid with max-width so that images do not stretch
- [x] Hover state for all of the buttons on the bottom
- [x] Pop up menus above the bottom menu

Hard Mode
- [ ] When a user clicks on the store item show the back side using a 3d card

**Comment by rtablada** [comment]
# Todo
- [ ] PR
- [ ] Link to PR
- [ ] Continue working on styles
- [ ] Responsive below 480px to one picture per row

**Comment by Brent-M-Thomas** [comment]
<a href="https://github.com/Brent-M-Thomas/1.4-Tshirts-Brent-Thomas/pull/1">Pull Request</a>

**Comment by Brent-M-Thomas** [comment]
@rtablada This should be done now

**Comment by rtablada** [comment]
@Brent-M-Thomas looks good, you should duplicate the menu under pictures 2&3
