### ISSUE TITLE
1.4-tshirts-Scott Green

### ISSUE THREAD

**Issue by scott6455** [TIY-LR-FEE-2015-June/assignments#38]
### Deliverables
- [x] a git repo containing:
  - [x] `index.html`
  - [x] stylesheets (in a `css/` directory)
  - [x] `images` folder
    - [x] with any images you used with your design
### Requirements
- [x] A pull request with code to recreate the layout and transitions below
- [x] 3 wide grid with max- [ ]width so that images do not stretch
- [ ] Hover state for all of the buttons on the bottom
- [ ] Pop up menus above the bottom menu
- [ ] Hard Mode
   When a user clicks on the store item show the back side using a 3d card
## Normal Mode
- [ ] Recreate the following layout in HTML and CSS:
- [ ] ![](./tshirts.gif)
## Notes

Notes go here...
- I have initially tried the 'line' and 'unit' you directed us to in the instructions so thats partly what is seen for the initial commit.

**Comment by rtablada** [comment]
# Todos
- [ ] Link to PR
- [ ] Set master as default branch
- [ ] WAAAA?

**Comment by scott6455** [comment]
https://github.com/scott6455/1.4-tshirts/pull/1

**Comment by scott6455** [comment]
https://github.com/scott6455/1.4-tshirts/pull/2

--not the finished file, im jsut checking somethings on github

**Comment by scott6455** [comment]
https://github.com/scott6455/1.4-tshirts/pull/4
