### ISSUE TITLE
1.4 hw tshirt -Coleman

### ISSUE THREAD

**Issue by ColemanCox** [TIY-LR-FEE-2015-June/assignments#39]
- [x] a git repo containing:
  -  [  ]  `index.html`
  - [x] stylesheets (in a `css/` directory)
  - [  ] `images` folder
    - with any images you used with your design
- [  ] A pull request with code to recreate the layout and transitions below
- [x] 3 wide grid with max-width so that images do not stretch
- [  ] Hover state for all of the buttons on the bottom
- [  ] Pop up menus above the bottom menu
- [  ] Hard Mode
  - When a user clicks on the store item show the back side using a 3d card
## Normal Mode
- [  ] Recreate the following layout in HTML and CSS:

**Comment by ColemanCox** [comment]
http://jsbin.com/vidopodogi/edit?html,css,output

Still trying to figure out some things. SO much information...

**Comment by rtablada** [comment]
# Todos:
- [ ] Link to your PR
- [ ] Make a centered row with 1/3 columns
- [ ] Menu below the photos

**Comment by ColemanCox** [comment]
https://github.com/ColemanCox/1.4-shirts/pull/1
