### ISSUE TITLE
1.4-t-shirts-Alia Borroho

### ISSUE THREAD

**Issue by aliaborroho** [TIY-LR-FEE-2015-June/assignments#41]
Deliverables
- [x] a git repo containing:
  - [x] `index.html`
  - [x] stylesheets (in a `css/` directory)
  - [x] `images` folder
    - [x] with any images you used with your design

Requirements
- [ ] A pull request with code to recreate the layout and transitions below
- [ ] 3 wide grid with max-width so that images do not stretch
- [ ] Hover state for all of the buttons on the bottom
- [ ] Pop up menus above the bottom menu
- [ ] Hard Mode
  - [ ] When a user clicks on

**Comment by rtablada** [comment]
# Todo
- [ ] Link to PR
- [ ] See your todos above

**Comment by rtablada** [comment]
@aliaborroho still look above. I am seeing an empty screen when I try to look at the code on your develop branch: 

https://github.com/aliaborroho/1.4-tshirts/blob/develop/index.html
