### ISSUE TITLE
1.4-tshits - Daniel Condit

### ISSUE THREAD

**Issue by DanielCondit** [TIY-LR-FEE-2015-June/assignments#42]
Deliverables
- [x] a git repo containing:
  - [x] `index.html`
  - [x] stylesheets (in a `css/` directory)
  -  [x] `images` folder
    - [x] with any images you used with your design

Requirements
- [x] A pull request with code to recreate the layout and transitions below
- [x] 3 wide grid with max-width so that images do not stretch
- [x] Hover state for all of the buttons on the bottom
- [x] Pop up menus above the bottom menu
- [ ] Hard Mode
  - [ ] When a user clicks on the store item show the back side using a 3d card

**Comment by rtablada** [comment]
# Todos:
- [ ] Link to Pull Request
- [ ] More Cage
- [ ] You know what you have to do

**Comment by rtablada** [comment]
@DanielCondit 

![Not sure if](http://cdn.meme.am/instances2/500x/751287.jpg)

![screen shot 2015-07-14 at 10 25 16 pm](https://cloud.githubusercontent.com/assets/2532004/8690239/7a1ddd48-2a77-11e5-906a-23de48920ade.png)

**Comment by DanielCondit** [comment]
pull request:

https://github.com/DanielCondit/1.4-tshirts/pull/1

**Comment by rtablada** [comment]
@DanielCondit the dropdowns are still unstyled a bit, but it is getting there

**Comment by DanielCondit** [comment]
List items open up. Ready for turn in.

**Comment by DanielCondit** [comment]
Complete

**Comment by rtablada** [comment]
@DanielCondit much better
