### ISSUE TITLE
2.1 - Beer Layout - Jacklyn Carroll

### ISSUE THREAD

**Issue by jacklynlee31** [TIY-LR-FEE-2015-June/assignments#43]
<h1>Deliverables</h1>

A repo containing at least:
- [x] main.css
- [x] index.html

<h1>Normal Mode</h1>

- [x] Create semantic markup that logical groups the content required for the page
- [x] Show a three wide grid on desktop screens
- [x] Show a list view layout on tablet screens < 1024px
- [x] Show a one wide grid layout on phone screens < 460px

**Comment by jacklynlee31** [comment]
https://github.com/jacklynlee31/2.1-beer-layout/pull/1

**Comment by rtablada** [comment]
# Todo
- [ ] See the comment I made: https://github.com/jacklynlee31/2.1-beer-layout/pull/1/files#r34307532
- [ ] After fixing your grid, the buttons still are at different heights, look at your `.text` selector and there should be one small change you can make

Should only be about 2 or 3 properties for the normal layout to be right
- [ ] On tablet mode, the buttons aren't quite lining up, this is similar to what is happening with vertical things on desktop mode

## Comments
- [ ] On phone view the text could be wider but you don't need to fix that, just a design choice
