### ISSUE TITLE
2.1-beer-layout-Daniel Condit

### ISSUE THREAD

**Issue by DanielCondit** [TIY-LR-FEE-2015-June/assignments#46]
Deliverables
- [x] A repo containing at least:
  - [x] `main.css`
  - [x] `index.html`

Normal Mode
- [x] Create semantic markup that logical groups the content required for the page
- [x] Show a three wide grid on desktop screens
- [x] Show a list view layout on tablet screens < 1024px
- [x] Show a one wide grid layout on phone screens < 460px

**Comment by DanielCondit** [comment]
https://github.com/DanielCondit/2.1-beer-layout/pull/1

ready for turn in

**Comment by rtablada** [comment]
# Todos
- Figure out lining things up on smaller tablet screens (maybe width using %?)

**Comment by rtablada** [comment]
@DanielCondit on further review, 
- the main container and row does not center up on the page
- You are also doing too much work on the phone media query, look back at the media query for tablet and see if you can change it to have both a min and max and see how that effects what you need to work on for phones
- There is no actual grid on desktop sizes: if expand the screen width the store goes to infinite wide: breaking the layout

![screen shot 2015-07-14 at 10 32 01 pm](https://cloud.githubusercontent.com/assets/2532004/8690304/4061ea3a-2a78-11e5-9a48-0c30f3af71be.png)

**Comment by DanielCondit** [comment]
Fixed issues with layout. Ready for turn in.

**Comment by DanielCondit** [comment]
Complete
