### ISSUE TITLE
2.1-Beer-Layout-Scott Green

### ISSUE THREAD

**Issue by scott6455** [TIY-LR-FEE-2015-June/assignments#48]
### Learning Objectives

After completing this assignment, you should…
- [ ] Understand HTML/CSS Layout
- [ ] Understand @media queries
- [ ] Be able to restyle and relayout elements at different screen sizes
### Performance Objectives

After completing this assignment, you be able to effectively use
- [ ] Use CSS Positioning
- [ ] Use `@media` queries with multiple requirements
### Deliverables
- [x] A repo containing at least:
  - [x] `main.css`
  - [x] `index.html`
## Normal Mode

Normal Mode description
- [ ] Create semantic markup that logical groups the content required for the page
- [ ] Show a three wide grid on desktop screens
- [ ] Show a list view layout on tablet screens < 1024px
- [ ] Show a one wide grid layout on phone screens < 460px
## Additional Resources
- [ ] [Learn CSS Layout](http://learnlayout.com/)

**Comment by rtablada** [comment]
# Todo
- [ ] Main file should be `index.html`
- [ ] Link to Pull Request

I am seeing a completely blank screen when I pull down your code.

**Comment by rtablada** [comment]
@scott6455 still missing a pr link

**Comment by scott6455** [comment]
https://github.com/scott6455/2.1-beer-layout/pull/1

**Comment by scott6455** [comment]
https://github.com/scott6455/2.1-beer-layout/pull/2
