### ISSUE TITLE
2.1-beer-layout-marvin-santiago

### ISSUE THREAD

**Issue by marvinsantiago** [TIY-LR-FEE-2015-June/assignments#50]
Deliverables

A repo containing at least:
- [x] main.css
- [x] index.html

Normal Mode description
- [x] Create semantic markup that logical groups the content required for the page
- [x] Show a three wide grid on desktop screens
- [x] Show a list view layout on tablet screens < 1024px
- [x] Show a one wide grid layout on phone screens < 460px

**Comment by santiagomarvin** [comment]
Deliverables

* [ ] A repo containing at least:
       * [ ] main.css
       * [ ] index.html
Normal Mode

Normal Mode description

* [ ] Create semantic markup that logical groups the content required for the page
* [ ] Show a three wide grid on desktop screens
* [ ] Show a list view layout on tablet screens < 1024px
* [ ] Show a one wide grid layout on phone screens < 460px

**Comment by marvinsantiago** [comment]
https://github.com/santiagomarvin/2.1-beer-layout/pull/1

**Comment by rtablada** [comment]
:star:

# Todos
- The photo looks a bit squished, try not setting both the height AND width only set one at a time
