### ISSUE TITLE
2.1-Beers-Coleman

### ISSUE THREAD

**Issue by ColemanCox** [TIY-LR-FEE-2015-June/assignments#52]
- [x] A repo containing at least:
- [x] main.css
- [x] index.html
  Normal Mode description
- [ ] Create semantic markup that logical groups the content required for the page
- [x] Show a three wide grid on desktop screens
- [ ] Show a list view layout on tablet screens < 1024px
- [ ] Show a one wide grid layout on phone screens < 460px

**Comment by rtablada** [comment]
# Todo
- [ ] Link to PR

---

Right now I am just seeing some basic HTML that isn't very semantic or representative of the underlying content.

All three (or more) beer items should have the same HTML elements and classes and only differ by the picture and text that they contain.

**Comment by ColemanCox** [comment]
I'll try to improve....

**Comment by rtablada** [comment]
@ColemanCox still missing a PR link
