### ISSUE TITLE
2.2-timeline-marvin-santiago

### ISSUE THREAD

**Issue by marvinsantiago** [TIY-LR-FEE-2015-June/assignments#55]
### Deliverables
- [x] A repo containing at least:
  - [x]  `public/index.html`
  - [x] stylesheets all in a `assets` directory
  - [x] `public/images` folder
    - [x] with any images you used with your design (you may use relevant placeholder images if needed)
### Requirements
- [x] An index.html with semantic HTML
  - [x] Componentized Timelines and Events
- [x] An SCSS file with at least
  - [x] One variable
  - [x] One import statement to bring in a third-party CSS file
- [x] Timeline styling
  - [x] Date
  - [x] Time
  - [x] Icon
  - [x] Event Name
  - [x] Description

**Comment by marvinsantiago** [comment]
https://github.com/santiagomarvin/2.2-timeline/pull/1

**Comment by marvinsantiago** [comment]
https://github.com/santiagomarvin/2.2-timeline/pull/1

**Comment by rtablada** [comment]
# Todo
- [x] Just check the icon

**Comment by marvinsantiago** [comment]
@rtablada - Made correction and now have icon on the line of timeline.

https://github.com/santiagomarvin/2.2-timeline/pull/1

**Comment by rtablada** [comment]
@santiagomarvin ![Cheers](http://media0.giphy.com/media/GCLlQnV7wzKLu/giphy.gif)
