### ISSUE TITLE
2.2-timeline-Daniel Condit

### ISSUE THREAD

**Issue by DanielCondit** [TIY-LR-FEE-2015-June/assignments#57]
Deliverables
- [x] A repo containing at least:
  - [x] `index.html`
  - [x] stylesheets (`scss/`, `css/`, and `dist/` folders)
  - [x] `images` folder
    - [x] with any images you used with your design

Requirements
- [x] An index.html with semantic HTML
  - [x] Componentized Timelines and Events
- [x] An SCSS file with at least
  - [x] One variable
  - [x] One import statement to bring in a third-party CSS file
- [x] Timeline styling
  - [x] Date
  - [x] Time
  - [x] Icon
    - [x] Event Name
    - [x] Description

**Comment by DanielCondit** [comment]
https://github.com/DanielCondit/2.2-timeline/pull/1

Took me forever to get everything organized, I feel I'm overcomplicating and taking unnecessary steps.

**Comment by rtablada** [comment]
@DanielCondit This started to get some of the requirements but there are some things to see when working with positioning.
Notice that since you positioned things outside of the parent, you then had to do some pretty hacky stuff and everything after it was affected and had to position EVERYTHING relative.
There is a better and simpler position option that will simplify things a lot and will clear up some of that muddiness.

# Review
- [ ] Look up position `static`, `relative`, `absolute` and `fixed` on [learnlayout.com](http://learnlayout.com)

See if you can get things a bit cleaner and less hacky.

---

I also noticed that your HTML is a bit more complicated that it needs to be.
For example, having an `h3` inside of `.title` div with nothing else inside of is redundant.
Same with things like `date` and `p`.
Clear this up.

# Todo
- [ ] Clear up positioning CSS/SCSS
- [ ] Simplify HTML

**Comment by DanielCondit** [comment]
Fixed css and html for timeline. Ready for turn in.

**Comment by rtablada** [comment]
@DanielCondit I don't see any commits pushed...? Maybe still just on your local box?
