### ISSUE TITLE
1.1 - Basic Git - Corbin Otwell

### ISSUE THREAD

**Issue by cbotwell** [TIY-LR-FEE-2015-June/assignments#6]
# Tasks
- [x] Create a new Issue with these tasks!
- [x] Use the Github web interface to create a repository called
  `1.1-Basic-Git`
- [x] Use the Github web interface to create a branch called on
  `1.1-Basic-Git` called `<initials>-develop`
- [x] In Github, open a PR _from_ `<initials>-develop` _into_ `master`
- [x] Create your personal website
  - [x] Checkpoint: Created and committed `index.html`
  - [x] Complete: Pushed `index.html`
#### Hard Mode Tasks
- [x] Checkpoint: Created and committed `main.css`

**Comment by cbotwell** [comment]
[Corbin's Pull Request](https://github.com/cbotwell/1.1-Basic-Git/pull/1)

**Comment by rtablada** [comment]
@cbotwell ticks all the boxes!

I have made one little note on your `main.css` file
