### ISSUE TITLE
2.2-timeline-Alia Borroho

### ISSUE THREAD

**Issue by aliaborroho** [TIY-LR-FEE-2015-June/assignments#61]
### Deliverables
- [x] A repo containing at least:
  - [x] `index.html`
  - [x] stylesheets (`scss/`, `css/`, and `dist/` folders)
  - [x] `images` folder
    - [x] with any images you used with your design
### Requirements
- [x] An index.html with semantic HTML
  - [ ] Componentized Timelines and Events
- [x] An SCSS file with at least
  - [ ] One variable
  - [ ] One import statement to bring in a third-party CSS file
- [ ] Timeline styling
  - [ ] Date
  - [ ] Time
  - [ ] Icon
  - [ ] Event Name
  - [ ] Description

**Comment by aliaborroho** [comment]
I've added everything, trying to make it jive, I do believe I may be a little code drunk. Will try to figure out the correct layout.

**Comment by aliaborroho** [comment]
<!DOCTYPE html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="app.css
  ">

  <title>Project Title</title>
</head>
<body>
	<ul class="timeline">
		<li class="Events">
			<h3>TIY day </h3>
			<p>it is the most mind-bending experience. I'm just writing because I dont know how to expolain the fear and the joy I am feeling.</p>
		</li>
	</ul>
	<ul class="timeline">
		<li class="Events">
			<h3>TIY day </h3>
			<p>it is the most mind-bending experience. I'm just writing because I dont know how to expolain the fear and the joy I am feeling.</p>
		</li>
	</ul>
		<ul class="timeline">
		<li class="Events">
			<h3>TIY day </h3>
			<p>it is the most mind-bending experience. I'm just writing because I dont know how to expolain the fear and the joy I am feeling.</p>
		</li>
	</ul>
		<ul class="timeline">
		<li class="Events">
			<h3>TIY day </h3>
			<p>it is the most mind-bending experience. I'm just writing because I dont know how to expolain the fear and the joy I am feeling.</p>
		</li>
	</ul>
</body>
</html>

**Comment by aliaborroho** [comment]
.timeline {
	border-left: 4px solid #000080;
	margin-left: 20%;

}

li {
	list-style: none;
}
.event {
	margin: .5rem;
	paddding: .5rem;
	padding-left: 1rem;
	border-radius: 3%;
}

li:nth-child(odd) {
	background-color: #6CB2E6;
}

li:nth-child(even) {
	background-color: #3E82BC;
}

**Comment by aliaborroho** [comment]
forgot to commit the html and the style sheet..

**Comment by rtablada** [comment]
@aliaborroho while I can grab the code you currently have, until a pull request is created and linked here, the assignment is considered incomplete.

Also, please update todo list above as well as the todos below

# Todo
- [ ] Create Pull Request on Github
- [ ] Paste link to pull request as a comment on this issue

Until turn

**Comment by rtablada** [comment]
@aliaborroho see above ^ I'm still missing a PR and link for this assignment

**Comment by aliaborroho** [comment]
https://github.com/aliaborroho/2.2-timeline/pull/1  @rtablada
