### ISSUE TITLE
2.3-photo-site-Daniel Condit

### ISSUE THREAD

**Issue by DanielCondit** [TIY-LR-FEE-2015-June/assignments#69]
Deliverables
- [x] A repo containing at least:
  - [x] The default file structure
- [x] Multiple SCSS partials files
- [x] A centralized set of variables to allow changing the site theme (grid sizes, color scheme, etc)
  - [x] A centralized set of variables to allow changing the site theme (grid sizes, color scheme, fonts, etc)
- [x] Your site hosted on Github Pages
  - [x] Link to your Github pages in the Issue for this assignment
    +\* [ ] At least one but no more than two Google Web Fonts
  
  Requirements
- [x] Your HTML and CSS should be valid.
  - [x] https://validator.w3.org/
  -  [x] http://csslint.net/
- [x] Styling for:
  - [x] Photos
  - [x] Icons
  - [x] Photo information
    - [x]  Title
    - [x]  Date
    - [x]  Camera Model
    - [x]  Sensor Size
    - [x]  fstop
    - [x]  ISO
    - [x]  Shutter Speed
  - [ ] Company Name Above Image ("Landscape")
  - [x] Responsive Style on Desktop
    - [x]  Photo Camera Info to the side of image
    - [x]  Photo Title and Date Below Photo
  - [x]  Hide Navbar Links On Mobile & Show Hamburger Icon
  - [x]  Footer Section
    - [ ] 2 wide photos with links and hover state
- [ ] Hard Mode Requirements:
  - [ ] Make the navbar shoot out from the side on mobile

**Comment by rtablada** [comment]
@DanielCondit do you have a link to your Pull Request or a build on GH Pages?

**Comment by DanielCondit** [comment]
pull request

https://github.com/DanielCondit/2.3-photo-site/pull/1

**Comment by DanielCondit** [comment]
http://danielcondit.github.io/2.3-photo-site/

**Comment by rtablada** [comment]
@DanielCondit 

# Todo
- The hamburger menu should only appear on phone screen sizes, otherwise show a list of links in the nav bar
- The Camera details should move under the picture on smaller screensizes
- You still need to work on the footer

**Comment by rtablada** [comment]
@DanielCondit ping me when you want me to review this again.

**Comment by DanielCondit** [comment]
Complete
