### ISSUE TITLE
2.3-Photo Site-Coleman Cox

### ISSUE THREAD

**Issue by ColemanCox** [TIY-LR-FEE-2015-June/assignments#74]
- A repo containing at least:
  - \- [ ] The default file structure
- [x] Multiple SCSS partials files
- [ ] A centralized set of variables to allow changing the site theme (grid sizes, color scheme, fonts, etc)
- [x] Your site hosted on Github Pages
  [ ] - Link to your Github pages in the Issue for this assignment
- [ ] At least one but no more than two Google Web Fonts
### Requirements
- [x] Your HTML and CSS should be valid.
  - https://validator.w3.org/
  - http://csslint.net/
- [ ] Styling for:
  - Photos
  - Icons
  - [x] Photo information
    - Title
    - Date
    - Camera Model
    - Sensor Size
    - f-stop
    - ISO
    - Shutter Speed
  - [x] Company Name Above Image ("Landscape")
  - [ ] Responsive Style on Desktop
    - [ ] Photo Camera Info to the side of image
    - [ ] Photo Title and Date Below Photo
  - [ ] Hide Navbar Links On Mobile & Show Hamburger Icon
  - [ ] Footer Section
    - [ ] 2 wide photos with links and hover state
- Hard Mode Requirements:
   [ ] - Make the navbar shoot out from the side on mobile

**Comment by ColemanCox** [comment]
- A repo containing at least:
  - \- [ ] The default file structure
- [x] Multiple SCSS partials files
- [ ] A centralized set of variables to allow changing the site theme (grid sizes, color scheme, fonts, etc)
- [ ] Your site hosted on Github Pages
  [ ] - Link to your Github pages in the Issue for this assignment
- [ ] At least one but no more than two Google Web Fonts

### Requirements
- [ ] Your HTML and CSS should be valid.
  - https://validator.w3.org/
  - http://csslint.net/
- [ ] Styling for:
  - Photos
  - Icons
  - [ ] Photo information
    - Title
    - Date
    - Camera Model
    - Sensor Size
    - f-stop
    - ISO
    - Shutter Speed
  - [ ] Company Name Above Image ("Landscape")
  - [ ] Responsive Style on Desktop
    - [ ] Photo Camera Info to the side of image
    - [ ] Photo Title and Date Below Photo
  - [ ] Hide Navbar Links On Mobile & Show Hamburger Icon
  - [ ] Footer Section
    - [ ] 2 wide photos with links and hover state
- Hard Mode Requirements:
   [ ] - Make the navbar shoot out from the side on mobile

## Normal Mode

**Comment by rtablada** [comment]
@ColemanCox you shouldn't need to repeat the todo list. You can click on the pencil at the top right of your original post to edit the contents of it.

The error you are getting is because you have not installed `bourbon` or `neat`: please see me this afternoon to get caught up on this topic.

# Todos
- [ ] Add `broccoli-sass` to your listed dependencies (remember to add `--save` when you are running `npm install`
- [ ] Publish to github pages - this is a special script we wrote on the day you were gone, please schedule a 1 on 1 with me to get caught up on this

**Comment by rtablada** [comment]
@ColemanCox still missing a link to your pull request and to a build on github pages.

**Comment by rtablada** [comment]
@ColemanCox ping me when you want me to look at this again, I know there's a lot on your todo list for now.

**Comment by ColemanCox** [comment]
https://github.com/ColemanCox/2.3-photo-site/pull/1

**Comment by ColemanCox** [comment]
http://colemancox.github.io/2.3-photo-site/

**Comment by rtablada** [comment]
@ColemanCox turned in, but still needs work
