### ISSUE TITLE
1.2-layout-basic

### ISSUE THREAD

**Issue by aliaborroho** [TIY-LR-FEE-2015-June/assignments#91]
Deliverables
- [x] a git repo containing:
  - [x] `index.html`
  - [x] `styles` folder
    - [x] `style.css`
  - [x] `images` folder
    - [x] with any images you used with your design
### Requirements
- [x] `index.html` Landing Page
- [x] `styles/style.css` css file linked from `index.html`
- [x] Page should have
  - [x] top image across the whole page
  - [x] badge on the left covering part of the top image
  - [x] multiple posts including different types of content using filler content
    - [x] heading text
    - [x] by line with author and date
    - [x] image
    - [x] lorem text after the image
- [x] Your HTML should pass in the HTML validator at [https://html5.validator.nu/](https://html5.validator.nu/)
- [ ] Hard requirements
  - [ ] Recreate the "Never miss a post section"
    - [ ] Should have an "x" in top right
    - [ ] Should stand off of the page visually
    - [ ] Should have image to the left of some stacked text
    - [ ] Should have colored button
- [ ] Extra hard requirements
  - [ ] Try building the left side bar where it says "the iron yard houston"

**Comment by aliaborroho** [comment]
pr:
https://github.com/aliaborroho/1.2-Layout-Basic/pull/1

**Comment by rtablada** [comment]
@aliaborroho 

# Todos
- [ ] There should be no room around the image at the top (check body margin)
- [ ] The image in the profile pic is not linked properly

![screen shot 2015-07-14 at 6 38 42 pm](https://cloud.githubusercontent.com/assets/2532004/8687599/96d3fb68-2a57-11e5-9882-e010886e82f2.png)

**Comment by aliaborroho** [comment]
Completed above

**Comment by rtablada** [comment]
@rtablada check this out now
